# Program IDs
programs:
  raydium:
    amm_v4: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
    ray_authority_v4: "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"
    api_v3_pools_info_url: "https://api-v3.raydium.io/pools/info/"
  openbook:
    program_id: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
  token:
    program_id: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    program_id_2022: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
  memo:
    v2: "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"

tokens:
  wsol:
    address: "So11111111111111111111111111111111111111112"
    decimal: 1000000000  # 10^9 (multiplier, not decimal places)
  default_quote_mint: "So11111111111111111111111111111111111111112"

constants:
  account_layout_len: 165

# Helius configuration
helius:
  wss_url: "https://mainnet.helius-rpc.com/?api-key="
  rpc_url: "https://mainnet.helius-rpc.com/?api-key="
  staked_rpc_url: "https://staked.helius-rpc.com?api-key="

# Solana configuration
solana:
  unit_budget: 150000
  unit_price: 1000000